### ISSUE TITLE
Disable Voice Over

### ISSUE THREAD

**Issue by essoojay** [Thaolga/luci-app-nekoclash#1]
Please how to disable the voice over permanently. 

Thank you

**Comment by Auroraxpm** [comment]
> 请问如何永久禁用画外音。
> 
> 谢谢

Now only keep website access detection; everything else can be turned off using the switch at the top.

**Comment by Auroraxpm** [comment]
Now only keep website access detection; everything else can be turned off using the switch at the top.

**Comment by essoojay** [comment]
system switch, weather report both disabled, current city not selected, but still you have youtube.. facebook... voice over!

maybe a switch to permanently disable all!..

thanks

**Comment by Auroraxpm** [comment]
I'll push a new version to disable website detection.

**Comment by Auroraxpm** [comment]
Update the plugin to version 1.2.3.
