### ISSUE TITLE
feature update

### ISSUE THREAD

**Issue by risunCode** [Thaolga/luci-app-nekoclash#2]
tambahin delay start kayak openclash.
![Uploading delaystart.PNG…]()

**Comment by risunCode** [comment]
![delaystart](https://github.com/user-attachments/assets/6ef46884-b62b-4b3d-b360-431a35bd3dc3)

**Comment by Auroraxpm** [comment]
You can manually edit the /etc/neko/core/neko file and add the following at the end.

while getopts ":skrpcvh" signal ; do
    case $signal in
        s)
            sleep 5  # Delay of 5 seconds before starting Mihomo Proxy
            neko_start
            ;;
