### ISSUE TITLE
mihomo configuration help

### ISSUE THREAD

**Issue by ingnelson** [Thaolga/luci-app-nekoclash#3]
Hello,

I installed the luci-app-nekoclash on my router with architercure mipsel_24kc , i have a probem trying to set up the configuration for mihomo . 
I have my own VPS and i have v2ray rurring there. i can use my android phone with V2RAY app and it working fine with my configuration. I tried many time to make it works in my router , but i failed to create the configuration. Could you help me , please ?

This is my configuration that i use on my v2ray , but i want to use it in my router with your tool 

`vless://683c305c-c9e1-4cd4-b645-7e2ceb02f283@216.238.76.64:443/?type=tcp&encryption=none&security=tls&sni=my.yahoo.com&alpn=h2%2Chttp%2F1.1#Mex-tcp`

or 

`- name: Mex-tcp
  type: vless
  server: 216.238.76.64
  port: 443
  uuid: 683c305c-c9e1-4cd4-b645-7e2ceb02f283
  cipher: auto
  tls: true
  alterId: 0
  flow: xtls-rprx-direct
  servername: my.yahoo.com
  udp: true
  skip-cert-verify: true `

Can you create a whole or full configuration this way i can only copy and paste it in the uci-app-nekoclash , please ?

**Comment by Auroraxpm** [comment]
You can directly use the link without the need for conversion, removing the "proxies:" at the beginning.

**Comment by Auroraxpm** [comment]
The default configuration is provided, and you can use it directly.

**Comment by ingnelson** [comment]
@Auroraxpm Can show me how to add it and use it with my configuration ? Because when i open chrome it does not change my ip or it does not make the tunnel .

Could you use my link and provide screenshots or video how to make it work , please ?

**Comment by Auroraxpm** [comment]
Join the Telegram group for feedback
