### ISSUE TITLE
能不能把首页的黄色背景留白啊

### ISSUE THREAD

**Issue by docker-master** [Thaolga/luci-app-nekoclash#4]
![image](https://github.com/user-attachments/assets/e2878bf0-214b-4e65-b4fb-f2893300e7ae)
感觉黄色的 不太搭，你看openclash留白就很好看，显得很干净
![image](https://github.com/user-attachments/assets/e24caed2-9bd2-43ce-9669-74d6bc83977d)

**Comment by Auroraxpm** [comment]
设定 ——主题设定——light.css

**Comment by docker-master** [comment]
还可以换主题，厉害，但是还是建议默认一个好看点的

**Comment by Auroraxpm** [comment]
有独立的管理面板不需要进op  ip/nekoclash
