### ISSUE TITLE
出个视频教程

### ISSUE THREAD

**Issue by docker-master** [Thaolga/luci-app-nekoclash#5]
看的出来，软件很强大，支持Mihomo内核 可以把clash.yaml文件迁移过来，使用了锚点，可以添加多个机场同时使用
可以切换Sing-box内核，还有转换模板，但是 如果想吸引大量用户的话 还是得把小白拉过来，出个视频教程最好啦

**Comment by ingnelson** [comment]
I agree, i would like a video tutorial showing different types of methods for instance TCP, VLESS ,VMESS connections like TLS that allow insecure ssl, websocket etc
