### ISSUE TITLE
无法使用

### ISSUE THREAD

**Issue by GuangYu-yu** [Thaolga/luci-app-nekoclash#9]
经常出现502错误
trojan节点被当作udp，并且无法使用
无法使用clash订阅自带规则
开机好像不能关闭自启
更新内核直接卡死

**Comment by Auroraxpm** [comment]
Mihomo支持通用格式订阅不用转换 你使用自带模板测试  转换模板下面有个个人版订阅可以使用自定义配置  你说的卡死 你可以终端输入nekoclash 进行更新

**Comment by GuangYu-yu** [comment]
在停用mihomo、更新配置、主页左上角设置按钮，有时候出现502错误，要重启路由器插件才能使用> Mihomo支持通用格式订阅不用转换 你使用自带模板测试  转换模板下面有个个人版订阅可以使用自定义配置  你说的卡死 你可以终端输入nekoclash 进行更新

**Comment by Auroraxpm** [comment]
主页左上角设置按钮 使用的是在线字库 要联网

**Comment by Auroraxpm** [comment]
> 在失效mihomo、更新配置、主页左上角设置按钮，偶尔会出现502错误，要重启路由器插件才能使用下面> Mihomo支持通用格式订阅不用转换使用自带模板测试转换模板有个人版本订阅可以使用自定义配置你说的卡死你可以终端输入nekoclash进行更新

以修改为本地 更新插件

**Comment by GuangYu-yu** [comment]
> > 在失效mihomo、更新配置、主页左上角设置按钮，偶尔会出现502错误，要重启路由器插件才能使用下面> Mihomo支持通用格式订阅不用转换使用自带模板测试转换模板有个人版本订阅可以使用自定义配置你说的卡死你可以终端输入nekoclash进行更新
> 
> 以修改为本地 更新插件

今天又试了一遍，还是用不了，报错Fatal error: Uncaught Error: Call to undefined function curl_init() in /www/nekoclash/personal.php:173 Stack trace: #0 /www/nekoclash/personal.php(295): saveSubscriptionContentToYaml('https://hj.zhxd...', 'hj.yaml') #1 /www/nekoclash/mon.php(253): include('/www/nekoclash/...') #2 {main} thrown in /www/nekoclash/personal.php on line 173

**Comment by Auroraxpm** [comment]
新仓库     https://github.com/Thaolga/openwrt-nekobox

**Comment by Auroraxpm** [comment]
卸载nekoclash 安装新版本
